### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'split' when calling util.prompt_for_user_token with a cached token of None scope

### ISSUE THREAD

**Issue by jj1118** [plamere/spotipy#176] opened 2017-03-29 03:07 UTC
Minimal example:
```Python
from spotipy.util import prompt_for_user_token
token = prompt_for_user_token(some_username, None, some_client_id, some_client_secret, some_redirect_uri)
# Now a cached token with None scope exists
token2 = prompt_for_user_token(some_username, None, some_client_id, some_client_secret, some_redirect_uri)
# AttributeError occurs
```
(Note `scope=None` is default for `util.prompt_for_user_token()`)
Traceback:
```Python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "$PYTHONPATH$\lib\site-packages\spotipy\util.py", line 56, in prompt_for_user_token
    token_info = sp_oauth.get_cached_token()
  File "$PYTHONPATH$\lib\site-packages\spotipy\oauth2.py", line 135, in get_cached_token
    if 'scope' not in token_info or not self._is_scope_subset(self.scope, token_info['scope']):
  File "$PYTHONPATH$\lib\site-packages\spotipy\oauth2.py", line 156, in _is_scope_subset
    needle_scope = set(needle_scope.split())
AttributeError: 'NoneType' object has no attribute 'split'
```
This breaks the program when being runned a second time with existence of cache on disk, which previously (back before last December I believe) did not happen.

**Comment by sachag678** [comment] 2017-04-02 20:28
I am having the same issue. It worked the first time but it fails the second time,

**Comment by anirudh3** [comment] 2017-04-11 09:03
Got the same issue!

**Comment by josduj** [comment] 2017-04-24 07:40
Use the github version, it should be fixed.

**Comment by jj1118** [comment] 2017-04-24 07:52
@josduj Using Github version, now the error becomes:
```Python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "$PYTHONPATH$\lib\site-packages\spotipy\util.py", line 56, in prompt_for_user_token
    token_info = sp_oauth.get_cached_token()
  File "$PYTHONPATH$\lib\site-packages\spotipy\oauth2.py", line 135, in get_cached_token
    if 'scope' not in token_info or not self._is_scope_subset(self.scope, token_info['scope']):
  File "$PYTHONPATH$\lib\site-packages\spotipy\oauth2.py", line 161, in _is_scope_subset
    return needle_scope <= haystack_scope
TypeError: unorderable types: NoneType() <= NoneType()
```

**Comment by sachag678** [comment] 2017-04-24 15:47
It started working for me.

I just deleted the original user token and now it works every time I use it

**Comment by arshadic** [comment] 2017-05-03 02:03
This issue is present on the "Shows the contents of every playlist owned by a user" example on the website documentation as well. fixed by setting scope='user-library-read' before prompting user token.

**Comment by ulgens** [comment] 2017-06-11 14:33
Simple workaround:

```
from json.decoder import JSONDecodeError
scope = <whatever_youwant>
try:
    token = util.prompt_for_user_token(username, scope, client_id, client_secret, redirect_uri)
except (AttributeError, JSONDecodeError):
    os.remove(f".cache-{username}")
    token = util.prompt_for_user_token(username, scope, client_id, client_secret, redirect_uri)
```

**Comment by diogofm** [comment] 2017-06-17 18:09
Thanks @ulgens , your solution worked fine for me.

**Comment by netik** [comment] 2017-06-28 19:09
Adding the following to _is_scope_subset in oauth2.py fixes this issue. When I initially created my oauth token I did it on a create_playlist call. It seems that this creates a token with a scope of None and that breaks parsing. This is working for me but may be an incomplete fix. 

```
     def _is_scope_subset(self, needle_scope, haystack_scope):
       if needle_scope == None and haystack_scope == None:
             return True
 
```

**Comment by gwynnebaer** [comment] 2017-07-07 23:39
I can confirm that @Perolus commit works for me.

**Comment by patalanov** [comment] 2017-08-02 21:51
how can one delete the original user token with None scope?

**Comment by patalanov** [comment] 2017-08-02 22:10
```
import os
from json.decoder import JSONDecodeError

scope = <whatever_youwant>
try:
    token = util.prompt_for_user_token(username, scope, client_id, client_secret, redirect_uri)
except (AttributeError, JSONDecodeError):
    os.remove(f".cache-{username}")
    token = util.prompt_for_user_token(username, scope, client_id, client_secret, redirect_uri)

```
this does not work for me. why do I get syntax error in  ```
os.remove(f".cache-{username}")
                                 ^
```
where is this file located?

**Comment by ulgens** [comment] 2017-08-03 06:57
> os.remove(f".cache-{username}")

f strings are only supporterd after python 3.6. If you're using lower version, you should use `.format()` method. File is located under same folder with the code itself.

**Comment by ivancete** [comment] 2018-03-19 18:07
Thanks @ulgens it worked very fine.

**Comment by jfaul** [comment] 2018-04-08 23:29
Hey @ivancete, I'm having the same problem you had, what was the code that you inserted using the .format()? Thanks!

**Comment by wyattshapiro** [comment] 2018-09-07 23:40
@jfaul The line of code using .format would be `os.remove(".cache-{}".format(username))`

**Comment by roydemirjian** [comment] 2018-10-16 19:11
@ulgens  worked perfectly thank you

**Comment by amirkatzster** [comment] 2019-02-10 08:03
A hidden file is created called .cache-{username} can be also deleted manually

**Comment by OliverPearmain** [comment] 2019-03-17 19:52
I was getting this problem because I wasn't passing the returned `token` when instanciating the `spotipy.Spotify` instance. 

I was doing this....
```
util.prompt_for_user_token("User")
spotify = spotipy.Spotify()
```

When I should have been doing this...
```
token = util.prompt_for_user_token("User")
spotify = spotipy.Spotify(auth=token)
```

**Comment by conorhennessy** [comment] 2019-03-28 03:35
Many thanks to @ulgens and @wyattshapiro whos fixes outlined above saved the day!

**Comment by mdreynes** [comment] 2019-08-26 18:50
I changed the function at line 155 with this

`    def _is_scope_subset(self, needle_scope, haystack_scope):
        if needle_scope:
            needle_scope = set(needle_scope.split())
        else:
            needle_scope = ""
        if haystack_scope:
            haystack_scope = set(haystack_scope.split())
        else:
            haystack_scope = ""

        return needle_scope <= haystack_scope`

and it works.

Maybe I've done something wrong (I have a lot to learn in Python) but for now is working

**Comment by ekinig** [comment] 2020-02-10 23:01
Hello. I was using the library without any trouble, but suddenly I got the same error. I am authenticating using:
import spotipy
from spotipy.oauth2 import SpotifyClientCredentials
```
client_credentials_manager = SpotifyClientCredentials(client_id=SPOT_CLIENT_ID,
                                                      client_secret=SPOT_CLIENT_SECRET)
sp = spotipy.Spotify(client_credentials_manager=client_credentials_manager)
```
I tried deleting the hidden file without luck. I am using the latest version of the library. Any ideas on what may be happening?

**Comment by nidhivanjare** [comment] 2021-04-30 14:10
I want to slipt the rows data by " " and count it 
```
start = datetime.now()
df_no_dup["tag_count"] = df_no_dup["Tags"].apply(lambda text: len(text.split(" ")))
# adding a new feature number of tags per question
print("Time taken to run this cell :", datetime.now() - start)
df_no_dup.head()
```

But I keep getting Attribute error :  'NoneType' object has no attribute 'split'


What do I do?

**Comment by stephanebruckert** [comment] 2021-06-26 20:44
Closing as wontfix as `util.prompt_for_user_token()` will be removed in v3

**Closed by stephanebruckert** 2021-06-26 20:44 UTC
Labels: bug, wontfix
