### ISSUE TITLE
I try example app.py but still got error AttributeError: module 'spotipy.cache_handler' has no attribute 'FlaskSessionCachceHandler'

### ISSUE THREAD

**Issue by febridev** [plamere/spotipy#838] opened 2022-07-10 11:36 UTC
I try using example code from this repo filename is app.py but I still got error 

`AttributeError: module 'spotipy.cache_handler' has no attribute 'FlaskSessionCachceHandler'`

I copy and paste and follow the instruction but still got error on above

when I change the attribute to MemoryCacheHandler I can't login

**Comment by Aspekto** [comment] 2022-07-11 18:25
That's because for some reason the spotipy that comes by using `pip install spotipy` isn't up to date with the github, so what I did to fix the issue is:
1. Setup a python venv in your project directory
    `cd your_project_dir`
    `python3 -m venv venv`
2. Install `spotipy` and your other packages if you need.
3. In your newly created `venv` folder, navigate to `venv/lib64/python3.10/site-packages/spotipy`
4. In that directory you will find a file called `cache_handler.py`, go [here](https://raw.githubusercontent.com/plamere/spotipy/master/spotipy/cache_handler.py) and copy that and paste it in that file.
5. Save and reload your project and that should work.

**Comment by stephanebruckert** [comment] 2022-08-22 17:34
Duplicate of https://github.com/plamere/spotipy/issues/838

**Closed by stephanebruckert** 2022-08-22 17:34 UTC
Labels: question
